<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel | layer | package | collection | component)>
<!ATTLIST SystemDefinition
  schema CDATA #REQUIRED
  id-namespace CDATA "http://www.symbian.org/system-definition"
>
<!-- this DTD describes schema="3.0.0" --> 

<!-- all relative paths are relative to this file
	all absolute paths are relative to the environment variable specified by the root attribute, or SRCROOT if not.  -->

<!-- Container for metadata
	meta, if present, should always be the first element in the parent 
	 -->
<!ELEMENT meta ANY>
<!ATTLIST meta
  href		CDATA #IMPLIED
  type	CDATA "auto"
  rel	CDATA "Generic"
>

<!-- systemModel element has name but no ID -->
<!ELEMENT systemModel (meta*, layer+)>
<!ATTLIST systemModel
  name CDATA #IMPLIED
>

<!-- All items from layer down to component should have either @href or at least one valid child item.
	Anything else will be considered a placeholder
	-->

<!ELEMENT layer (meta*, (package | collection)*)  >
<!ATTLIST layer
  id ID #REQUIRED
  name CDATA #IMPLIED
  href		CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  before NMTOKEN #IMPLIED
>

<!ELEMENT package (meta*,  (package | collection)*)>
 <!-- Nested packages are for backwards compatibility only -->
<!ATTLIST package
  id ID #REQUIRED
  name CDATA #IMPLIED
  version CDATA #IMPLIED
  tech-domain CDATA #IMPLIED
  href	 CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  before NMTOKEN #IMPLIED  
>

<!ELEMENT collection (meta*, (component* ))>
<!ATTLIST collection
  id ID #REQUIRED
  name CDATA #IMPLIED
  href		CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  before NMTOKEN #IMPLIED  
>

<!ELEMENT component (meta*, unit*)>
<!-- contains units or is a placeholder -->
<!ATTLIST component
  id ID #REQUIRED
  name CDATA #IMPLIED
  href		CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  target  ( device | desktop | other ) "device"
  purpose ( optional | mandatory | development ) "optional"  
  class NMTOKENS #IMPLIED
  filter CDATA #IMPLIED
  before NMTOKEN #IMPLIED  
  origin-model CDATA #IMPLIED
>
<!--
	"filter" attribute is deprecated
	"origin-model" attribute is only to be inserted by tools when merging models
 	recommended class values are: doc, config, plugin, tool, api -->

<!ELEMENT unit EMPTY >
<!ATTLIST unit
  mrp CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  base CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (yes|no) #IMPLIED
  filter CDATA #IMPLIED
  priority CDATA #IMPLIED
>
<!-- filter and priority are deprecated 
	"root" attribute will usually be inserted by tools when merging models, although it can be set manually-->
]>
<SystemDefinition schema="3.0.0">
  <systemModel name="Symbian^4">
    <layer id="adapt" name="Adaptation" levels="low mw high">
      <package id="openmaxil.nokia" tech-domain="mm" level="high" href="../../../../adapt/openmaxil.nokia/package_definition.xml"/>
    </layer>
    <layer id="os" name="OS" levels="hw services">
      <package id="kernelhwsrv" level="hw" tech-domain="hb" href="../../../../os/kernelhwsrv/package_definition.xml"/>
      <package id="boardsupport" level="hw" tech-domain="hb" href="../../../../os/boardsupport/package_definition.xml"/>
      <package id="buildtools" level="hw" tech-domain="to" href="../../../../os/buildtools/package_definition.xml"/>
      <package id="ossrv" level="services" tech-domain="hb" href="../../../../os/ossrv/package_definition.xml"/>
      <package id="security" level="services" tech-domain="se" href="../../../../os/security/package_definition.xml"/>
      <package id="persistentdata" level="services" tech-domain="hb" href="../../../../os/persistentdata/package_definition.xml"/>
      <package id="devicesrv" level="services" tech-domain="hb" href="../../../../os/devicesrv/package_definition.xml"/>
      <package id="lbs" level="services" tech-domain="lo" href="../../../../os/lbs/package_definition.xml"/>
      <package id="commsfw" level="services" tech-domain="dc" href="../../../../os/commsfw/package_definition.xml"/>
      <package id="networkingsrv" level="services" tech-domain="dc" href="../../../../os/networkingsrv/package_definition.xml"/>
      <package id="wlan" level="services" tech-domain="dc" href="../../../../os/wlan/package_definition.xml"/>
      <package id="cellularsrv" level="services" tech-domain="vc" href="../../../../os/cellularsrv/package_definition.xml"/>
      <package id="bt" level="services" tech-domain="de" href="../../../../os/bt/package_definition.xml"/> 
      <package id="usb" level="services" tech-domain="de" href="../../../../os/usb/package_definition.xml"/> 
      <package id="mm" level="services" tech-domain="mm" href="../../../../os/mm/package_definition.xml"/>
      <package id="imagingext" level="services" tech-domain="mm" href="../../../../os/imagingext/package_definition.xml"/>
      <package id="graphics" level="services" tech-domain="ui" href="../../../../os/graphics/package_definition.xml"/>
      <package id="textandloc" level="services" tech-domain="ui" href="../../../../os/textandloc/package_definition.xml"/>
      <package id="xmlsrv" level="services" tech-domain="rt" href="../../../../os/xmlsrv/package_definition.xml"/>
      <package id="deviceplatformrelease" level="services" tech-domain="to" href="../../../../os/deviceplatformrelease/package_definition.xml"/>
      <package id="osrndtools" level="services" tech-domain="to" href="../../../../os/osrndtools/package_definition.xml"/>
      <package id="mmimaging" level="services" tech-domain="mm" href="../../../../os/mmimaging/package_definition.xml"/>
      <package id="openmaxil" level="services" tech-domain="mm" href="../../../../os/openmaxil/package_definition.xml"/>
    </layer>
    <layer id="mw" name="Middleware" levels="generic specific">
      <package id="appsupport" level="generic" tech-domain="rt" href="../../../../mw/appsupport/package_definition.xml"/>
      <package id="securitysrv" level="generic" tech-domain="se" href="../../../../mw/securitysrv/package_definition.xml"/>
      <package id="drm" level="generic" tech-domain="se" href="../../../../mw/drm/package_definition.xml"/>
      <package id="locationsrv" level="specific" tech-domain="lo" href="../../../../mw/locationsrv/package_definition.xml"/>
      <package id="accesssec" level="generic" tech-domain="dc" href="../../../../mw/accesssec/package_definition.xml"/>
      <package id="ipconnmgmt" level="generic" tech-domain="dc" href="../../../../mw/ipconnmgmt/package_definition.xml"/>
      <package id="netprotocols" level="generic" tech-domain="dc" href="../../../../mw/netprotocols/package_definition.xml"/>
      <package id="ipappprotocols" level="generic" tech-domain="dc" href="../../../../mw/ipappprotocols/package_definition.xml"/>
      <package id="wirelessacc" level="specific" tech-domain="dc" href="../../../../mw/wirelessacc/package_definition.xml"/>
      <package id="vpnclient" level="specific" tech-domain="dc" href="../../../../mw/vpnclient/package_definition.xml"/>
      <package id="ipappsrv" level="specific" tech-domain="vc" href="../../../../mw/ipappsrv/package_definition.xml"/>
      <package id="phonesrv" level="specific" tech-domain="vc" href="../../../../mw/phonesrv/package_definition.xml"/>
      <package id="messagingmw" level="specific" tech-domain="pr" href="../../../../mw/messagingmw/package_definition.xml"/>
      <package id="imsrv" level="specific" tech-domain="pr" href="../../../../mw/imsrv/package_definition.xml"/>
      <package id="legacypresence" level="specific" tech-domain="pr" href="../../../../mw/legacypresence/package_definition.xml"/>
      <package id="opensrv" level="specific" tech-domain="pr" href="../../../../mw/opensrv/package_definition.xml"/>
      <package id="remotemgmt" level="specific" tech-domain="dm" href="../../../../mw/remotemgmt/package_definition.xml"/>
      <package id="networkingdm" level="generic" tech-domain="dm" href="../../../../mw/networkingdm/package_definition.xml"/>
      <package id="remotestorage" level="generic" tech-domain="de" href="../../../../mw/remotestorage/package_definition.xml"/>
      <package id="remoteconn" level="generic" tech-domain="de" href="../../../../mw/remoteconn/package_definition.xml"/>
      <package id="srvdiscovery" level="generic" tech-domain="de" href="../../../../mw/srvdiscovery/package_definition.xml"/>
      <package id="dlnasrv" level="specific" tech-domain="de" href="../../../../mw/dlnasrv/package_definition.xml"/>
      <package id="btservices" level="generic" tech-domain="de" href="../../../../mw/btservices/package_definition.xml"/>
      <package id="usbservices" level="generic" tech-domain="de" href="../../../../mw/usbservices/package_definition.xml"/>
      <package id="imghandling" level="specific" tech-domain="mm" href="../../../../mw/imghandling/package_definition.xml"/>
      <package id="metadatasrv" level="specific" tech-domain="mm" href="../../../../mw/metadatasrv/package_definition.xml"/>
      <package id="mds" level="specific" tech-domain="mm" href="../../../../mw/mds/package_definition.xml"/>
      <package id="mmuifw" level="specific" tech-domain="mm" href="../../../../mw/mmuifw/package_definition.xml"/>
      <package id="videoutils" level="specific" tech-domain="mm" href="../../../../mw/videoutils/package_definition.xml"/>
      <package id="mmmw" level="generic" tech-domain="mm" href="../../../../mw/mmmw/package_definition.xml"/>
      <package id="helix" level="generic" tech-domain="mm" name="Helix"/>
      <package id="camerasrv" level="specific" tech-domain="mm" href="../../../../mw/camerasrv/package_definition.xml"/>
      <package id="mmappfw" level="specific" tech-domain="mm"  href="../../../../mw/mmappfw/package_definition.xml"/>
      <package id="inputmethods" level="generic" tech-domain="ui" href="../../../../mw/inputmethods/package_definition.xml"/>
      <package id="classicui" level="generic" tech-domain="ui" href="../../../../mw/classicui/package_definition.xml"/>
      <package id="svgt" level="generic" tech-domain="ui" href="../../../../mw/svgt/package_definition.xml"/>
      <package id="uiaccelerator" level="generic" tech-domain="ui" href="../../../../mw/uiaccelerator/package_definition.xml"/>
      <package id="uiresources" level="generic" tech-domain="ui" href="../../../../mw/uiresources/package_definition.xml"/>
      <package id="hapticsservices" level="generic" tech-domain="ui" href="../../../../mw/hapticsservices/package_definition.xml"/>
      <package id="gsprofilesrv" level="generic" tech-domain="ui" href="../../../../mw/gsprofilesrv/package_definition.xml"/>
      <package id="homescreensrv" level="specific" tech-domain="ui" href="../../../../mw/homescreensrv/package_definition.xml"/>
      <package id="appinstall" level="generic" tech-domain="rt" href="../../../../mw/appinstall/package_definition.xml"/>
      <package id="serviceapifw" level="specific" tech-domain="rt" href="../../../../mw/serviceapifw/package_definition.xml"/>
      <package id="serviceapi" level="specific" tech-domain="rt" href="../../../../mw/serviceapi/package_definition.xml"/>
      <package id="web" level="specific" tech-domain="rt" href="../../../../mw/web/package_definition.xml"/>
      <package id="websrv" level="generic" tech-domain="rt" href="../../../../mw/websrv/package_definition.xml"/>
      <package id="platformtools" level="generic" tech-domain="to" href="../../../../mw/platformtools/package_definition.xml"/>
      <package id="uitools" level="specific" tech-domain="to" href="../../../../mw/uitools/package_definition.xml"/>
    </layer>
    <layer id="app" name="Applications" levels="services apps">
      <package id="location" level="apps" tech-domain="lo" href="../../../../app/location/package_definition.xml"/>
      <package id="mmsharinguis" level="services" tech-domain="vc" href="../../../../app/mmsharinguis/package_definition.xml"/>
      <package id="phone" level="apps" span="2" tech-domain="vc" href="../../../../app/phone/package_definition.xml"/>
      <package id="videotelephony" level="apps" tech-domain="vc" href="../../../../app/videotelephony/package_definition.xml"/>
      <package id="poc" level="apps" tech-domain="vc" href="../../../../app/poc/package_definition.xml"/>
      <package id="iptelephony" level="apps" tech-domain="vc" href="../../../../app/iptelephony/package_definition.xml"/>
      <package id="settingsuis" level="services" tech-domain="dm" href="../../../../app/settingsuis/package_definition.xml"/>
      <package id="contentcontrol" level="services" tech-domain="dm" href="../../../../app/contentcontrol/package_definition.xml"/>
      <package id="devicecontrol" level="services" tech-domain="dm" href="../../../../app/devicecontrol/package_definition.xml"/>
      <package id="printing" level="services" tech-domain="de" href="../../../../app/printing/package_definition.xml"/>
      <package id="files" level="apps" tech-domain="pr" href="../../../../app/files/package_definition.xml"/>
      <package id="contacts" level="apps" span="2" tech-domain="pr" href="../../../../app/contacts/package_definition.xml"/>
      <package id="organizer" level="apps" span="2" tech-domain="pr" href="../../../../app/organizer/package_definition.xml"/>
      <package id="messaging" level="apps" span="2" tech-domain="pr" href="../../../../app/messaging/package_definition.xml"/>
      <package id="commonemail" level="apps" span="2" tech-domain="pr" href="../../../../app/commonemail/package_definition.xml"/>
      <package id="conversations" level="apps" tech-domain="pr" href="../../../../app/conversations/package_definition.xml"/>
      <package id="im" level="apps" tech-domain="pr" href="../../../../app/im/package_definition.xml"/>
      <package id="utils" level="apps" tech-domain="pr" href="../../../../app/utils/package_definition.xml"/>
      <package id="dictionary" level="services" tech-domain="pr" href="../../../../app/dictionary/package_definition.xml"/>
      <package id="camera" level="apps" tech-domain="ma" href="../../../../app/camera/package_definition.xml"/>
      <package id="imgeditor" level="apps" tech-domain="ma" href="../../../../app/imgeditor/package_definition.xml"/>
      <package id="videoeditor" level="apps" tech-domain="ma" href="../../../../app/videoeditor/package_definition.xml"/>
      <package id="gallery" level="apps" tech-domain="ma" href="../../../../app/gallery/package_definition.xml"/>
      <package id="videoplayer" level="apps" tech-domain="ma" href="../../../../app/videoplayer/package_definition.xml"/>
      <package id="photos" level="apps" tech-domain="ma" href="../../../../app/photos/package_definition.xml"/>
      <package id="videocenter" level="apps" tech-domain="ma" href="../../../../app/videocenter/package_definition.xml"/>
      <package id="musicplayer" level="apps" tech-domain="ma" href="../../../../app/musicplayer/package_definition.xml"/>
      <package id="radio" level="apps" tech-domain="ma" href="../../../../app/radio/package_definition.xml"/>
      <package id="voicerec" level="apps" tech-domain="ma" href="../../../../app/voicerec/package_definition.xml"/>
      <package id="imgvieweruis" level="services" tech-domain="ma" href="../../../../app/imgvieweruis/package_definition.xml"/>
      <package id="screensaver" level="apps" tech-domain="ui" href="../../../../app/screensaver/package_definition.xml"/>
      <package id="homescreen" level="apps" tech-domain="ui" href="../../../../app/homescreen/package_definition.xml"/>
      <package id="graphicsuis" level="services" tech-domain="ui" href="../../../../app/graphicsuis/package_definition.xml"/>
      <package id="profile" level="apps" tech-domain="ui" href="../../../../app/profile/package_definition.xml"/>
      <package id="speechsrv" level="services" tech-domain="ui" href="../../../../app/speechsrv/package_definition.xml"/>
      <package id="homescreentools" level="services" tech-domain="ui"  href="../../../../app/homescreentools/package_definition.xml"/>
      <package id="webuis" level="services" tech-domain="rt" href="../../../../app/webuis/package_definition.xml"/>
      <package id="java" level="services" tech-domain="rt" href="../../../../app/java/package_definition.xml"/>
      <package id="conntools" level="services" tech-domain="dc" href="../../../../app/conntools/package_definition.xml"/>
      <package id="rndtools" level="services" tech-domain="to" href="../../../../app/rndtools/package_definition.xml"/>
      <package id="helps" level="apps" span="2" tech-domain="ui" href="../../../../app/helps/package_definition.xml"/>
      <package id="techview" level="apps" span="2" tech-domain="ui" href="../../../../app/techview/package_definition.xml"/>
    </layer>
  </systemModel>
</SystemDefinition>
